Repository loverajoel/theproductindex, pull requests merged in 2019-08, with the labels that each got.

#13 mvp rewrite
  docs/competitive-market.md
  docs/designing-and-running-experiments.md
  docs/images/mvp-tests-matrix.png
  docs/minimum-viable-product.md
Labels: Content

#12 Section: Introduction to Product Management
  docs/introduction-to-product-management.md
Labels: Resources

#14 product development rewrite
  docs/building-the-product.md
  docs/images/kanban-board.png
  docs/images/scrum-vs-kanban.png
  docs/images/scrum.png
  docs/images/waterfall.png
  docs/product-development.md
Labels: Content

#16 Metrics rewrite
  docs/images/research-methods-framework.png
  docs/images/retention-curve.png
  docs/measuring-product-success.md
  docs/metrics.md
Labels: Content, Resources

#17 Growth rewrite
  docs/growth-foundations.md
  docs/growth.md
  docs/images/growth-levers-image.png
Labels: Content, Fix typo/Update Grammar, Resources
